# Build stage
FROM maven:3.8.4-openjdk-11 AS build
WORKDIR /app
COPY backend/pom.xml .
RUN mvn dependency:go-offline

COPY backend/src /app/src
RUN mvn package -DskipTests

# Run stage
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]